name: mapbox_gl_example
description: Demonstrates how to use the mapbox_gl plugin.
publish_to: 'none'

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  image_picker: ^0.6.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_mapbox_gl:
    path: ../


flutter:
  uses-material-design: true
  assets:
    - res/southeast_radar_0.png
    - res/southeast_radar_1.png
    - res/southeast_radar_2.png
    - res/southeast_radar_3.png
    - res/style.json
    - res/red_marker.png
    - res/iss.png
    - res/la_heatmap_styling_points.geojson
    - res/bathymetry-data.geojson
    - res/ic_cross.png
    - res/example.geojson
    - res/fake_norway_campsites.geojson
    - res/white_house_lvl_0.geojson
    - res/white_house_lvl_1.geojson
    - res/pink_dot.png
    - res/matched_route.geojson
