name: mapbox_gl
description: A new Flutter project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  strings: any
  protobuf: any
  built_value: any
  built_collection: any
  pub_semver: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  build_runner: any
  built_value_generator: any

flutter:
  plugin:
    androidPackage: com.tophap.mapbox_gl
    pluginClass: MapboxGlPlugin