name: flutter_mapbox_gl
description: A new Flutter project.
version: 0.0.5
author: Razvan Lung <lung.razvan@gmail.com>
homepage: https://www.tophap.com

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  strings: ^0.1.0
  protobuf: ^0.14.1
  built_value: ^6.7.1
  built_collection: ^4.2.2
  pub_semver: ^1.4.2
  meta: ^1.1.7
  path: ^1.6.4
  fixnum: ^0.10.9
  collection: ^1.14.0
  grpc: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  flutter_driver:
    sdk: flutter
  build_runner: ^1.5.0
  built_value_generator: ^6.7.1

flutter:
  plugin:
    androidPackage: com.tophap.mapbox_gl
    pluginClass: MapboxGlPlugin